[build-system]
requires = [
    "poetry>=0.12"
]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "dnsrobocert"
version = "0.1.0"
description = "A tool to manage your DNS-challenged TLS certificates"
license = "MIT"
keywords = [
    "dnsrobocert"
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "License :: OSI Approved :: MIT License",
    "Operating System :: Unix", "Operating System :: POSIX",
    "Operating System :: Microsoft :: Windows",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Utilities"
]
authors = [
    "Adrien Ferrand"
]
readme = "README.md"
include = [
    "src/dnsrobocert/schema.yml"
]

[tool.poetry.dependencies]
python = "^3.6"
certbot = "==1.3.0"
cryptography = "^2.8"
dns-lexicon = "==3.3.17"
dnspython3 = "^1.15"
jsonschema = "^3.2"
pem = "^20.1"
pyopenssl = "^19.1"
pyyaml = "^5.3"
schedule = "^0.6"
coloredlogs = "^14.0"
colorama = "^0.4"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
flake8 = "^3.7"
mypy = "^0.761"
pytest = "^5.3"
pytest-cov = "^2.8"
isort = "^4.3"

[tool.poetry.scripts]
dnsrobocert = "dnsrobocert.core.main:main"
