jobs:
  - job: package-pypi
    pool:
      vmImage: ubuntu-18.04
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: 3.8
          addToPath: true
        displayName: Install Python
      - script: |
          python -m pip install -U pip
          pip install poetry
        displayName: Prepare environment
      - script: |
          poetry build
        displayName: Build distribution

  - job: docker
    pool:
      vmImage: ubuntu-18.04
    steps:
      - task: Docker@2
        inputs:
          repository: $(imageName)
          command: build
        displayName: Build Docker image
