jobs:
  - job: package
    pool:
      vmImage: ubuntu-18.04
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: $(PYTHON_VERSION)
          addToPath: true
        displayName: Install Python
      - script: |
          python -m pip install -U pip
          pip install poetry
        displayName: Prepare environment
      - script: |
          poetry build
        displayName: Build distribution
