version: '3.7'

services:
  dnsrobocert:
    image: adferrand/dnsrobocert
    container_name: dnsrobocert
    env_file: .env
    volumes:
      - $ROOT/dnsrobocert.yml:/etc/letsencrypt/dnsrobocert.yml
      - $ROOT/:/etc/letsencrypt
    environment:
      - VERSION=latest
    restart: always
