version: '3.7'

services:
  letsencrypt:
    image: adferrand/letsencrypt-dns
    container_name: "letsencrypt-dns"
    env_file: .env
    volumes:
      - "$ROOT/domains.conf:/etc/letsencrypt/domains.conf"
      - "$ROOT/certs/:/etc/letsencrypt"
    environment:
      - VERSION=latest
      - "LETSENCRYPT_USER_MAIL=$EMAIL"
      - "LEXICON_PROVIDER=$PROVIDER"
      - "LEXICON_PROVIDER_OPTIONS=$PROVIDER_OPTIONS"
      - "CERTS_DIRS_MODE=$DIRS_MODE"
      - "CERTS_FILES_MODE=$FILES_MODE"
    restart: always
