pr:
  - master

jobs:
  - job: test
    strategy:
      matrix:
        macos-py36:
          IMAGE_NAME: macOS-10.14
          PYTHON_VERSION: 3.6
          TOXENV: py36
        macos-py38:
          IMAGE_NAME: macOS-10.14
          PYTHON_VERSION: 3.8
          TOXENV: py38
        windows-py36:
          IMAGE_NAME: windows-2019
          PYTHON_VERSION: 3.6
          TOXENV: py36
        windows-py38:
          IMAGE_NAME: windows-2019
          PYTHON_VERSION: 3.8
          TOXENV: py38
        linux-py36:
          IMAGE_NAME: ubuntu-18.04
          PYTHON_VERSION: 3.6
          TOXENV: py36
        linux-py38:
          IMAGE_NAME: ubuntu-18.04
          PYTHON_VERSION: 3.8
          TOXENV: py38-cover
        flake8:
          IMAGE_NAME: ubuntu-18.04
          PYTHON_VERSION: 3.8
          TOXENV: flake8
        mypy:
          IMAGE_NAME: ubuntu-18.04
          PYTHON_VERSION: 3.8
          TOXENV: mypy
    pool:
      vmImage: $(IMAGE_NAME)
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: $(PYTHON_VERSION)
          addToPath: true
        displayName: Install Python
      - script: |
          python -m pip install -U pip
          pip install tox
        displayName: Install tox
      - script: |
          tox
        displayName: Run tox
