trigger:
  branches:
    exclude:
      - "*"
  tags:
    include:
      - "3.*"

pr: none

stages:
  - stage: package
    jobs:
      - template: templates/delivery-jobs.yml
  - stage: deploy
    jobs:
      - template: templates/deploy-jobs.yml
#  - stage: tests
#    jobs:
#      - template: templates/integration-jobs.yml